<?php
$to_complete_cars = [
    "Mon super pouvoir, c’est ____.",
    "Le plus gros scandale politique de l’année implique ____.",
    "Pendant mon temps libre, j'aime me déguiser en ____.",
    "Si je pouvais changer une seule chose dans le monde, ce serait ____.",
    "L’invention du siècle, c’est ____.",
    "Rien ne me fait plus peur que ____.",
    "Si je pouvais dîner avec une personne célèbre, je choisirais ____.",
    "Mon médecin m'a prescrit ____ pour calmer mes nerfs.",
    "Le prochain projet de Netflix s’appelle ____.",
    "J'ai été expulsé de l'école parce que j'ai apporté ____.",
    "Si les aliens nous attaquent, notre seule défense sera ____.",
    "Ma nouvelle stratégie pour attirer l’attention sur Tinder : ____.",
    "Le secret de la longévité, c’est ____.",
    "Les vacances de rêve pour moi, ce serait de passer une semaine à ____.",
    "Dans 50 ans, les historiens se souviendront de 2024 comme l'année de ____.",
    "La recette secrète de ma grand-mère contient un ingrédient spécial : ____.",
    "La seule chose qui pourrait améliorer cette fête, c'est ____.",
    "Le prochain film Marvel s'appellera ‘Avengers : ____’.",
    "Mon plan infaillible pour conquérir le monde commence par ____."
];
$completion_cards = [
    "Un poney rose en colère.",
    "Un karaoké avec des chèvres.",
    "Une invasion de canards en plastique.",
    "L'odeur du vieux fromage.",
    "Des chaussettes sales sous l’oreiller.",
    "Un rendez-vous romantique à Ikea.",
    "Le retour des jeans taille basse.",
    "Manger une pizza froide à 3h du matin.",
    "Les conseils beauté de Vladimir Poutine.",
    "Un iguane qui fait du yoga.",
    "La danse de la pluie sous MDMA.",
    "Des toilettes publiques au milieu de la jungle.",
    "Un jacuzzi rempli de soupe.",
    "Mon ex qui fait la une des journaux.",
    "Les plans secrets de la NASA pour coloniser Disneyland.",
    "Une séance de méditation dirigée par un chat.",
    "Des croquettes bio pour humains.",
    "Un orgasme provoqué par une feuille d’arbre.",
    "Le retour des dinosaures.",
    "Une rave dans une boulangerie."
];